import sys
import os

# print("abc")
source = sys.argv[1]

lines = []
lines.append("#!/bin/bash")
lines.append("# NOTE: generated by buildgen.py")
lines.append("")
lines.append("""CALVER=$(date '+v%Y_%m_%d')""")

lines.append("")

name = source.split(".")[0]

lines.append(f"""WINEXE="{name}32$""" '''{CALVER}.exe"''')
lines.append(f"""LINEXE="{name}32$""" '''{CALVER}.linux"''')

lines.append("")

lines.append('''echo "Building $WINEXE and $LINEXE"''')

lines.append(
    """zig cc -s -o "$WINEXE" snore.c -O3 -DSNORE_VERSION="\\"$CALVER\\"" -target x86-windows-gnu &"""
)
lines.append(
    """zig cc -s -o "$LINEXE" snore.c -O3 -DSNORE_VERSION="\\"$CALVER\\"" -target x86-linux-musl &"""
)
lines.append("""wait""")
lines.append("")

lines.append("""if [ "$1" == "install" ]; then""")
lines.append('''    echo "installing"''')
lines.append(f"""    cp "$WINEXE" /g/mybin/{name}.exe""")
lines.append("""fi""")


if not os.path.isfile("build.sh"):
    if os.path.exists("build.sh"):
        print("File build.sh is not a regular file.")
    else:
        print("File build.sh doesn't exist.")
    sys.exit(1)

with open("build.sh", "wb") as f:
    f.write("\n".join(lines).encode("ASCII"))
print("Wrote out build.sh")
