import shlex
import sys
import os

# print("abc")
source = sys.argv[1]

lines = []
lines.append("#!/bin/bash")
lines.append("# NOTE: generated by buildgen.py " + shlex.join(sys.argv[1:]))
lines.append("")
lines.append("""CALENDAR_VERSION=$(date '+v%Y_%m_%d')""")

lines.append("")

name = source.split(".")[0]

lines.append(f"""WINEXE="{name}32$""" '''{CALENDAR_VERSION}.exe"''')
lines.append(f"""LINEXE="{name}32$""" '''{CALENDAR_VERSION}.linux"''')

lines.append("")

lines.append('''echo "Building $WINEXE and $LINEXE"''')

lines.append(
    f"""zig cc -s -o "$WINEXE" {source} -O3 -DCALENDAR_VERSION="\\"$CALENDAR_VERSION\\"" -target x86-windows-gnu &"""
)
lines.append(
    f"""zig cc -s -o "$LINEXE" {source} -O3 -DCALENDAR_VERSION="\\"$CALENDAR_VERSION\\"" -target x86-linux-musl &"""
)
lines.append("""wait""")
lines.append("")

lines.append("""if [ "$1" == "install" ]; then""")
lines.append('''    echo "installing"''')
lines.append(f"""    cp "$WINEXE" /g/mybin/{name}.exe""")
lines.append("""fi""")


if not os.path.isfile("build.sh"):
    if os.path.exists("build.sh"):
        print("File build.sh is not a regular file.")
    else:
        print("File build.sh doesn't exist.")
    sys.exit(1)

with open("build.sh", "rb") as f:
    oldcontent = f.read()

lines.append("")  # empty line at the end o file ends with a newline
content = "\n".join(lines).encode("ASCII")
if content == oldcontent:
    print("build.sh is already up to date")
else:
    with open("build.sh", "wb") as f:
        f.write(content)
    print("Wrote out build.sh")
